CREATE TABLE TB_USUARIO_COMUM (
    ID VARCHAR PRIMARY KEY NOT NULL,
    NOME VARCHAR NOT NULL,
    ROLE VARCHAR NOT NULL,

    CONSTRAINT FK_ID_OCORRENCIA FOREIGN KEY (ID_OCORRENCIA) REFERENCES TB_OCORRENCIA(ID);
);

CREATE TABLE TB_FUNCIONARIO (
    ID VARCHAR PRIMARY KEY NOT NULL,
    NOME VARCHAR NOT NULL,
    SETOR VARCHAR NOT NULL,
    ROLE VARCHAR NOT NULL,
);

CREATE TABLE TB_LOGIN_USUARIO_COMUM (
    ID VARCHAR PRIMARY KEY NOT NULL,
    EMAIL VARCHAR NOT NULL UNIQUE,
    SENHA VARCHAR NOT NULL,

    CONSTRAINT FK_ID_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO_COMUM(ID);
);

CREATE TABLE TB_LOGIN_FUNCIONARIO (
    ID VARCHAR PRIMARY KEY NOT NULL,
    EMAIL VARCHAR NOT NULL UNIQUE,
    SENHA VARCHAR NOT NULL,

    CONSTRAINT FK_ID_FUNCIONARIO FOREIGN KEY (ID_FUNCIONARIO) REFERENCES TB_FUNCIONARIO(ID)
);

CREATE TABLE TB_OCORRENCIA (
    ID VARCHAR PRIMARY KEY NOT NULL,
    DESCRICAO VARCHAR NOT NULL,
    RUA VARCHAR NOT NULL,
    BAIRRO VARCHAR NOT NULL,
    CEP VARCHAR NOT NULL,
    IMAGEM BOTH,
    TIPO_IMAGEM VARCHAR,
    HORA TIME NOT NULL,
    DATA DATE NOT NULL,
    STATUS VARCHAR NOT NULL,
    CATEGORIA VARCHAR NOT NULL,

    CONSTRAINT FK_ID_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO_COMUM(ID)
);

